hydra:
  run:
    dir: ./experiments/${name}/${now}/seed=${seed}
  sweep:
    dir: ./experiments/${name}/${now}
  job:
    config:
      override_dirname:
        item_sep: '_'
        exclude_keys:
          - seed
          - name

defaults:
  - launcher: slurm
  - inference_algo: svi
  - override hydra/launcher: submitit_slurm

name: test_baselines
seed: 0